version = 1

[*]
# Global Surgical Baseline (Shared across all models)
host = 127.0.0.1
port = 8080
flash-attn = on
no-mmap = true
threads = 16
threads-batch = 16
parallel = 1

[qwen2.5-coder-32b-instruct-q4_K_M]
model = .\models\qwen2.5-coder_32b-instruct-q4_K_M.gguf
n-gpu-layers = 50
tensor-split = 0.6,0.4
ctx-size = 16384
cache-type-k = q4_0
cache-type-v = q4_0

[qwen2.5-coder-14b-instruct-q4_K_M]
model = .\models\qwen2.5-coder-14b-instruct-q4_K_M.gguf
n-gpu-layers = 80
tensor-split = 0.5,0.5
ctx-size = 32768
cache-type-k = q8_0
cache-type-v = q8_0

[qwen3-14b-q4_k_s]
n-gpu-layers = 80
tensor-split = 0.5,0.5
ctx-size = 32768
cache-type-k = q4_0
cache-type-v = q4_0

[granite-4.0-h-small-Q4_K_M]
model = .\models\granite-4.0-h-small-Q4_K_M.gguf
n-gpu-layers = 41
main-gpu = 1
tensor-split = 0.62,0.38
ctx-size = 131072
cache-type-k = q4_0
cache-type-v = q4_0

[granite-4.0-h-tiny-Q4_K_M]
model = .\models\granite-4.0-h-tiny-Q4_K_M.gguf
n-gpu-layers = 41
main-gpu = 1
tensor-split = 0,1
ctx-size = 131072
cache-type-k = q4_0
cache-type-v = q4_0

[gemma-2-9b-instruct-Q6_K]
model = .\models\gemma-2-9b-instruct-Q6_K.gguf
main-gpu = 1
n-gpu-layers = 80
tensor-split = 0.5,0.5
ctx-size = 32768
cache-type-k = q8_0
cache-type-v = q8_0

[gemma-4-E4B-it-Q4_K_M]
model = .\models\gemma-4-E4B-it-Q4_K_M.gguf
main-gpu = 1
n-gpu-layers = 80
tensor-split = 0.5,0.5
ctx-size = 131072
cache-type-k = q4_0
cache-type-v = q4_0